### ISSUE TITLE
ACVP Proxy Linux Lineup Question

### ISSUE THREAD

**Issue by jramage77** [smuellerDD/acvpproxy#4]
Hi Stephan - first of all thanks much for the proxy and parser application!!!

I have been experimenting with the proxy using CentOS 7 and have a working solution but I think I have a mixed environment of original (distro) and new openssl and curl apps/libs that produce inconsistent results depending on my LD_LIBRARY_PATH setting. 

Could you please share your lineup of: linux O/S and version, openssl and curl - also indicate if you needed  the devel packages for the above apps or not. A few words about NIST certificates setup would be helpful too please (in addition to the json config file setup).

Thanks, James.

**Comment by smuellerDD** [comment]
Am Freitag, 21. Dezember 2018, 16:34:01 CET schrieb jramage77:

Hi jramage77,

> Hi Stephan - first of all thanks much for the proxy and parser
> application!!!
> 
> I have been experimenting with the proxy using CentOS 7 and have a working
> solution but I think I have a mixed environment of original (distro) and
> new openssl and curl apps/libs that produce inconsistent results depending
> on my LD_LIBRARY_PATH setting.
> 
> Could you please share your lineup of: linux O/S and version, openssl and
> curl - also indicate if you needed  the devel packages for the above apps
> or not. A few words about NIST certificates setup would be helpful too
> please (in addition to the json config file setup).

I use Fedora 29 which has contemporary software versions.

You need the devel package for curl and libc to build the proxy.

You need the devel packages for libc to build the parser. In addition you need 
the header files of your backend.

If you use the OpenSSL backend that is upstreamed together with the parser, it 
is developed against Fedora 29 and is intended for OpenSSL 1.1.x (NOT OpenSSL 
1.0.x!). The reason is that OpenSSL 1.1.x was yet uncovered and Fedora 29 has 
the only FIPS-compliant OpenSSL version as part of the default installation.

If you want to test a different OpenSSL, you need to modify the 
backend_openssl.c appropriately.

Ciao
Stephan

**Comment by jramage77** [comment]
Thanks much for your prompt reply Stephan - I will proceed with your guidance using Fedora 29 and associated instructions. I will close this issue but may have further questions in the future.
Cheers and Happy Holidays!
